typography_spectrum: 0.13558649574406445
color:
  brandStrength: 0.44040371174924076
  lightness: 0.4343321295455098
  saturation: 0.02204001322388649
  rhythmicContrast: 0.38695865543559194
  brandColors:
    - '#A3C1D9'
    - '#040E06'
    - '#517E9B'
    - '#F1FAF9'
    - '#1D3F64'
layout_spectrum: 0.12735915114171803
name: BudowSKI Report
title: NO SNOW HERE
